name: Push Test
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  push_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: auto-update
      - name: Create Test File
        run: |
          mkdir -p test
          echo "test" > ${{ github.workspace }}/test/test.txt
      - name: Commit Test File
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ secrets.GIT_USERNAME }}
          git add .
          git commit -m "Push Test"
      - name: Push Test File
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
          branch: ${{ github.ref }}
          force_with_lease: true