name: Update All
on:
  workflow_dispatch:
jobs:
  update-arknights:
    name: Update Arknights
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ArknightsStory in Kaggle
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: update-arknights-story
          code_file: .github/scripts/ArknightsStory.py
          language: python
          kernel_type: script
          enable_gpu: enable
          enable_internet: enable
      - name: Upload Data
        uses: actions/upload-artifact@v3
        with:
          name: arknights-parquet
          path: /home/runner/work/_actions/Frederisk/kaggle-action/v1.0.0/ArknightsStory.parquet
  update-genshin:
    name: Update Genshin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GenshinReadable in Kaggle
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: update-genshin-readable
          code_file: .github/scripts/GenshinReadable.py
          language: python
          kernel_type: script
          enable_gpu: enable
          enable_internet: enable
      - name: Run GenshinSubtitle in Kaggle
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: update-genshin-subtitle
          code_file: .github/scripts/GenshinSubtitle.py
          language: python
          kernel_type: script
          enable_gpu: enable
          enable_internet: enable
      - name: Run GenshinTextMap in Kaggle
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: update-genshin-textmap
          code_file: .github/scripts/GenshinTextMap.py
          language: python
          kernel_type: script
          enable_gpu: enable
          enable_internet: enable
      - name: Upload Data
        uses: actions/upload-artifact@v3
        with:
          name: genshin-parquet
          path: |
            /home/runner/work/_actions/Frederisk/kaggle-action/v1.0.0/GenshinReadable.parquet
            /home/runner/work/_actions/Frederisk/kaggle-action/v1.0.0/GenshinSubtitle.parquet
            /home/runner/work/_actions/Frederisk/kaggle-action/v1.0.0/GenshinTextMap.parquet
  update-repo:
    needs:
      - update-arknights
      - update-genshin
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.gdfscjy.com"
      - name: Download Data
        uses: actions/download-artifact@v3
        with:
          path: ./download
      - run: |
            find ./download -mindepth 2 -type f -exec mv -i '{}' ./download ';'
            find ./download -mindepth 1 -type d -exec rm -rf '{}' ';'
            rm -rf ./parquet
            mv ./download ./parquet
            git add .
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
      - run: pip install pandas pyarrow tabulate
      - name: Update README
        run: |
          python .github/update-readme.py
          git add .
      - name: Commit changes
        run: |
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
