name: Update All
on:
  workflow_dispatch:
jobs:
  update-arknights:
    name: Update Arknights
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ArknightsStory in Kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kernel_title: update-arknights-story
          kernel_id: ${{ secrets.KAGGLE_USERNAME }}/update-arknights-story
          code_file_path: .github/scripts/ArknightsStory.py
          language: python
          kernel_type: script
          is_private: true
          enable_gpu: true
          enable_internet: true
          collect_output: true
  update-genshin:
    name: Update Genshin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GenshinReadable in Kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kernel_title: update-genshin-readable
          kernel_id: ${{ secrets.KAGGLE_USERNAME }}/update-genshin-readable
          code_file_path: .github/scripts/GenshinReadable.py
          language: python
          kernel_type: script
          is_private: true
          enable_gpu: true
          enable_internet: true
          collect_output: true
      - name: Run GenshinSubtitle in Kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kernel_title: update-genshin-subtitle
          kernel_id: ${{ secrets.KAGGLE_USERNAME }}/update-genshin-subtitle
          code_file_path: .github/scripts/GenshinSubtitle.py
          language: python
          kernel_type: script
          is_private: true
          enable_gpu: true
          enable_internet: true
          collect_output: true
      - name: Run GenshinTextMap in Kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kernel_title: update-genshin-textmap
          kernel_id: ${{ secrets.KAGGLE_USERNAME }}/update-genshin-textmap
          code_file_path: .github/scripts/GenshinTextMap.py
          language: python
          kernel_type: script
          is_private: true
          enable_gpu: true
          enable_internet: true
          collect_output: true
  update-repo:
    needs:
      - update-arknights
      - update-genshin
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.gdfscjy.com"
      - name: Download Data
        uses: actions/download-artifact@v3
        with:
          path: ./download
      - run: |
            find ./download -mindepth 2 -type f -exec mv -i '{}' ./download ';'
            find ./download -mindepth 1 -type d -exec rm -rf '{}' ';'
            rm -rf ./parquet
            mv ./download ./parquet
            git add .
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
      - run: pip install pandas pyarrow tabulate
      - name: Update README
        run: |
          python .github/update-readme.py
          git add .
      - name: Commit changes
        run: |
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
