name: Update All

on:
  workflow_dispatch:
jobs:
  update-data:
    strategy:
      max-parallel: 2
      matrix:
        kaggle_username: [${{ secrets.KAGGLE_USERNAME }}]
        kaggle_key: [${{ secrets.KAGGLE_KEY }}]
        language: [python]
        kernel_type: [script]
        is_private: [true]
        enable_gpu: [true]
        enable_internet: [true]
        save_outputs: [true]
        outputs_path: [outputs]
        upload_to_artifact: [true]
        include:
          - title: Arknights Story
            code_file: ./.github/scripts/ArknightsStory.py
          - title: Genshin Readable
            code_file: ./.github/scripts/GenshinReadable.py
          - title: Genshin Subtitle
            code_file: ./.github/scripts/GenshinSubtitle.py
          - title: Genshin TextMap
            code_file: ./.github/scripts/GenshinTextMap.py
    uses: ./.github/workflows/update.yml
    with:
      kaggle_username: ${{ matrix.kaggle_username }}
      kaggle_key: ${{ matrix.kaggle_key }}
      title: ${{ matrix.title }}
      code_file: ${{ matrix.code_file }}
      language: ${{ matrix.language }}
      kernel_type: ${{ matrix.kernel_type }}
      is_private: ${{ matrix.is_private }}
      enable_gpu: ${{ matrix.enable_gpu }}
      enable_internet: ${{ matrix.enable_internet }}
      save_outputs: ${{ matrix.save_outputs }}
      outputs_path: ${{ matrix.outputs_path }}
      upload_to_artifact: ${{ matrix.upload_to_artifact }}

  update-repo:
    needs:
      - update
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.gdfscjy.com"
      - name: Download Data
        uses: actions/download-artifact@v3
        with:
          path: ./download
      - run: |
          find ./download -mindepth 2 -type f -exec mv -i '{}' ./download ';'
          find ./download -mindepth 1 -type d -exec rm -rf '{}' ';'
          rm -rf ./parquet
          mv ./download ./parquet
          git add .
      - name: Update README
        run: |
          pip install pandas pyarrow tabulate
          python .github/update-readme.py
          git add .
      - name: Commit changes
        run: |
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
