name: Update All
on:
  workflow_dispatch:
jobs:
  update_data:
    strategy:
      max-parallel: 2
      matrix:
        include:
          - title: Arknights Story
            code_file: ./.github/scripts/ArknightsStory.py
          - title: Genshin Readable
            code_file: ./.github/scripts/GenshinReadable.py
          - title: Genshin Subtitle
            code_file: ./.github/scripts/GenshinSubtitle.py
          - title: Genshin TextMap
            code_file: ./.github/scripts/GenshinTextMap.py
    uses: ./.github/workflows/update.yml
    with:
      title: ${{ matrix.title }}
      code_file: ${{ matrix.code_file }}
      language: python
      kernel_type: script
      is_private: true
      enable_gpu: true
      enable_internet: true
      save_outputs: true
      outputs_path: outputs
      upload_to_artifact: true
    secrets:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
  update_repo:
    needs:
      - update
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.gdfscjy.com"
      - name: Download Data
        uses: actions/download-artifact@v3
        with:
          path: ./download
      - run: |
          find ./download -mindepth 2 -type f -exec mv -i '{}' ./download ';'
          find ./download -mindepth 1 -type d -exec rm -rf '{}' ';'
          rm -rf ./parquet
          mv ./download ./parquet
          git add .
      - name: Update README
        run: |
          pip install pandas pyarrow tabulate
          python .github/update-readme.py
          git add .
      - name: Commit changes
        run: |
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
